#!/bin/bash
awk '
BEGIN {
        lines=0;
        FS="|";
        for(i=3;i<6;i++)
            {
                min[i]=1000000;
                max[i]=0;
                total[i]=0;
                square[i]=0
            }
}

{
    lines+=1;
    for(i=3;i<6;i++)
    {
        if(min[i]>$i)
            min[i]=$i;
        if(max[i]<$i)
            max[i]=$i;
        total[i]=total[i]+$i;
        square[i]=square[i] + $i^2;
    }

    print $0,"|",$3+$4+$5;
}

END {
    print "max    |       |"max[3]"|"max[4]"|"max[5],"| "max[3]+max[4]+max[5];
    print "min    |       |"min[3]"|"min[4]"|"min[5],"| "min[3]+min[4]+min[5];
    print "mean   |       |    "total[3]/lines " |    "total[4]/lines" |    "total[5]/lines" | "(total[3]+total[4]+total[5])/lines;
    for(i=3;i<6;i++)
    {
        sd[i]=sqrt((square[i]-lines*((total[i]/lines)^2))/lines);
    }
    print "sd     |       |"sd[3]"|"sd[4]"|"sd[5],"| "sd[3]+sd[4]+sd[5];
}'

